# Generated by Django 4.2.5 on 2023-09-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('refacturedb', '0003_alter_message_user_alter_room_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('custom_fields', models.JSONField(blank=True, null=True, verbose_name='custom fields')),
                ('urn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='urn')),
                ('callback_url', models.TextField(blank=True, null=True, verbose_name='Callback URL')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('ended_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ended by')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('is_waiting', models.BooleanField(default=False, verbose_name='is waiting for answer?')),
                ('transfer_history', models.JSONField(blank=True, null=True, verbose_name='Transfer History')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomss', to='refacturedb.contact', verbose_name='contact')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomss', to='refacturedb.queue', verbose_name='Queue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomss', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('seen', models.BooleanField(default=False, verbose_name='Was it seen?')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess', to='refacturedb.contact', verbose_name='contact')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagess', to='refacturedb.room', verbose_name='room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
