# Generated by Django 4.2.5 on 2023-09-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refacturedb', '0004_roomtext_messagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetext',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagess', to='refacturedb.roomtext', verbose_name='room'),
        ),
    ]
