# Generated by Django 4.2.5 on 2023-09-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacturedb', '0005_alter_messagetext_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='index',
            field=models.TextField(blank=True, null=True, verbose_name='Index'),
        ),
    ]
