# Generated by Django 4.2.5 on 2023-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refacturedb', '0006_messagetext_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetext',
            name='index',
        ),
    ]
